"""initial schema

Revision ID: 20260928_0001
Revises:
Create Date: 2026-09-28 14:56:16.452583
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260928_0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        op.f("ix_audit_events_correlation_id"), "audit_events", ["correlation_id"], unique=False
    )
    op.create_index(
        "ix_audit_events_type_created", "audit_events", ["event_type", "created_at"], unique=False
    )
    op.create_table(
        "oauth_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_states")),
        sa.UniqueConstraint("state_hash", name=op.f("uq_oauth_states_state_hash")),
    )
    op.create_index(
        op.f("ix_oauth_states_expires_at"), "oauth_states", ["expires_at"], unique=False
    )
    op.create_table(
        "olx_chats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.String(length=255), nullable=False),
        sa.Column("list_id", sa.String(length=128), nullable=False),
        sa.Column("buyer_name", sa.String(length=255), nullable=True),
        sa.Column("buyer_email", sa.String(length=320), nullable=True),
        sa.Column("buyer_phone", sa.String(length=64), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_olx_chats")),
        sa.UniqueConstraint("chat_id", name=op.f("uq_olx_chats_chat_id")),
    )
    op.create_index(op.f("ix_olx_chats_list_id"), "olx_chats", ["list_id"], unique=False)
    op.create_table(
        "olx_credentials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("access_token_encrypted", sa.Text(), nullable=False),
        sa.Column("token_type", sa.String(length=32), nullable=False),
        sa.Column(
            "connection_status",
            sa.Enum(
                "disconnected",
                "authorized",
                "connected",
                "reauthorization_required",
                name="connection_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("last_401_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "connection_status IN ('disconnected', 'authorized', 'connected', "
            "'reauthorization_required')",
            name=op.f("ck_olx_credentials_connection_status_values"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_olx_credentials")),
    )
    op.create_index(
        op.f("ix_olx_credentials_connection_status"),
        "olx_credentials",
        ["connection_status"],
        unique=False,
    )
    op.create_table(
        "olx_listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("list_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "price IS NULL OR price >= 0", name=op.f("ck_olx_listings_price_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_olx_listings")),
        sa.UniqueConstraint("list_id", name=op.f("uq_olx_listings_list_id")),
    )
    op.create_index(op.f("ix_olx_listings_status"), "olx_listings", ["status"], unique=False)
    op.create_table(
        "telegram_updates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("update_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "processed",
                "rejected",
                "failed",
                name="telegram_update_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('received', 'processed', 'rejected', 'failed')",
            name=op.f("ck_telegram_updates_status_values"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_updates")),
        sa.UniqueConstraint("update_id", name=op.f("uq_telegram_updates_update_id")),
    )
    op.create_index(
        op.f("ix_telegram_updates_status"), "telegram_updates", ["status"], unique=False
    )
    op.create_table(
        "olx_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.String(length=255), nullable=False),
        sa.Column("chat_id", sa.String(length=255), nullable=False),
        sa.Column("list_id", sa.String(length=128), nullable=False),
        sa.Column("origin", sa.String(length=32), nullable=False),
        sa.Column("sender_type", sa.String(length=32), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("olx_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("telegram_message_id", sa.BigInteger(), nullable=True),
        sa.Column("telegram_chat_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["olx_chats.chat_id"],
            name=op.f("fk_olx_messages_chat_id_olx_chats"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_olx_messages")),
        sa.UniqueConstraint("message_id", name=op.f("uq_olx_messages_message_id")),
        sa.UniqueConstraint(
            "telegram_message_id", name=op.f("uq_olx_messages_telegram_message_id")
        ),
    )
    op.create_index(
        "ix_olx_messages_chat_received", "olx_messages", ["chat_id", "received_at"], unique=False
    )
    op.create_index(op.f("ix_olx_messages_list_id"), "olx_messages", ["list_id"], unique=False)
    op.create_table(
        "outbound_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_update_id", sa.BigInteger(), nullable=False),
        sa.Column("olx_chat_id", sa.String(length=255), nullable=False),
        sa.Column("olx_reference_message_id", sa.String(length=255), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "sending",
                "sent",
                "retry",
                "failed",
                "unknown",
                "dead_letter",
                name="outbound_message_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("olx_http_status", sa.Integer(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'sending', 'sent', 'retry', 'failed', 'unknown', 'dead_letter')",
            name=op.f("ck_outbound_messages_status_values"),
        ),
        sa.CheckConstraint(
            "attempts >= 0", name=op.f("ck_outbound_messages_attempts_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["olx_chat_id"],
            ["olx_chats.chat_id"],
            name=op.f("fk_outbound_messages_olx_chat_id_olx_chats"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["olx_reference_message_id"],
            ["olx_messages.message_id"],
            name=op.f("fk_outbound_messages_olx_reference_message_id_olx_messages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["telegram_update_id"],
            ["telegram_updates.update_id"],
            name=op.f("fk_outbound_messages_telegram_update_id_telegram_updates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbound_messages")),
        sa.UniqueConstraint(
            "telegram_update_id", name=op.f("uq_outbound_messages_telegram_update_id")
        ),
    )
    op.create_index(
        "ix_outbound_messages_status_next_attempt",
        "outbound_messages",
        ["status", "next_attempt_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_outbound_messages_status_next_attempt", table_name="outbound_messages")
    op.drop_table("outbound_messages")
    op.drop_index(op.f("ix_olx_messages_list_id"), table_name="olx_messages")
    op.drop_index("ix_olx_messages_chat_received", table_name="olx_messages")
    op.drop_table("olx_messages")
    op.drop_index(op.f("ix_telegram_updates_status"), table_name="telegram_updates")
    op.drop_table("telegram_updates")
    op.drop_index(op.f("ix_olx_listings_status"), table_name="olx_listings")
    op.drop_table("olx_listings")
    op.drop_index(op.f("ix_olx_credentials_connection_status"), table_name="olx_credentials")
    op.drop_table("olx_credentials")
    op.drop_index(op.f("ix_olx_chats_list_id"), table_name="olx_chats")
    op.drop_table("olx_chats")
    op.drop_index(op.f("ix_oauth_states_expires_at"), table_name="oauth_states")
    op.drop_table("oauth_states")
    op.drop_index("ix_audit_events_type_created", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_correlation_id"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
